// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lokqongxioqbesejavdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxva3Fvbmd4aW9xYmVzZWphdmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MDA4MDIsImV4cCI6MjA5MDE3NjgwMn0.AssUc8nJbbrcQbG5kVnlehCAw89Xy-kdh0Hg_9JlMi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Bypass navigator.locks — evita "Lock broken by another request with the 'steal' option"
    // quando há múltiplas instâncias (preview + HMR). Seguro para uso single-tab.
    lock: async (_name, _acquireTimeout, fn) => await fn(),
  }
});
